version: '3'
services:
  app:
    image: app:1
    container_name: app
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    links:
      - postgres
    networks:
        - network1
  postgres:
    image: 'postgres:10.8-alpine'
    container_name: postgres
    volumes:
      - './server/scripts:/home/populate'
      - './server/data:/var/lib/postgresql/data:cached'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - DEBUG_COLORS=true
networks:
  network1: