version: '3'
services:
  app:
    image: app:1
    container_name: app
    build:
      context: ./
      dockerfile: Dockerfile.4
    ports:
      - "8080:8080"
    networks:
        - network1
networks:
  network1: